require('dotenv').config();
const Discord = require('discord.js')
const Client = new Discord.Client();

let onOrOff = false;

Client.on('message', (message) => {
    if (message.author.username != Client.user.username) {
        if (message.content == '--on') {
            onOrOff = true;
            message.channel.send('Turned on :thumbsup:');
        } else if (message.content == '--off') {
            onOrOff = false;
            message.channel.send('Turned off :thumbsup:');
        }
    }
})

Client.on('message', (message) => {
    if (onOrOff == true) {
        if (message.author.username != Client.user.username) {
            message.channel.send('AJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAJAJAJAJAJAJAJJAAJJAJJAJAJAJAJAJAJAJAJAJJAJAJAJAJAJ')
        }
    }
})

Client.on('ready', () => {
    console.log(`Logged in as ${Client.user.tag}`);
})

Client.login(process.env.JAJAJ_TOKEN);